package constants;

public enum RobotState {
	DEFAULT,
	INITIAL_HOLDING_HATCH,
	INITIAL_HOLDING_BALL,
	HATCH_SCORE,
	WAITING_TO_LOAD,
	LOADING_HATCH,
	HATCH_PRESCORE,
	LOADING_BALL,
	BALL_PRESCORE,
	BALL_FRONT_SCORE,
	BALL_BACK_SCORE,
	DEFENSE,
	CLIMB
	
}