package constants;

public class RunConstants {
	public static boolean
		RUNNING_DRIVE = false,
		RUNNING_LEADSCREW = true,
		RUNNING_PNEUMATICS = true,
		RUNNING_HATCH = RUNNING_PNEUMATICS && true,
		RUNNING_CAMERA = true,
		SECONDARY_JOYSTICK = true,
		IS_PROTOTYPE = false,
		
		RUNNING_EVERYTHING = RUNNING_DRIVE && RUNNING_PNEUMATICS && RUNNING_LEADSCREW && RUNNING_HATCH && SECONDARY_JOYSTICK;
}